---
title: "R Notebook"
output: html_notebook
---


```{r setup, include=FALSE}
source("D:/AGH/INZ/kod/setup.R", local = knitr::knit_global())
# or sys.source("your-script.R", envir = knitr::knit_global())
print("setup in kod_shapefiles - success")
```


# SHAPEFILES

```{r}

print(getwd())
#MALOPOLSKIE & PODKARPACKIE
south <- st_read("Wojewodztwa/poludnie.shp")
#Projected CRS: ETRS89 / Poland CS92

south <- st_transform(south, crs = 4326)
#Geodetic CRS:  WGS 84

south <- st_geometry(south)
south <- st_union(south)
south
#plot(south)



#WIELKOPOLSKIE & KUJAWSKO-POMORSKIE
north <- st_read("Wojewodztwa/polnoc.shp")
#Projected CRS: ETRS89 / Poland CS92
  
north <- st_transform(north, crs = 4326)
#Geodetic CRS:  WGS 84

north <- st_geometry(north)
north <- st_union(north)
north
#plot(north)


both <- st_union(south, north)
```

```{r}
#MALOPOLSKIE & PODKARPACKIE
#w <- st_read("Wojewodztwa/Województwa.shp")
#Projected CRS: ETRS89 / Poland CS92

#w <- st_transform(w, crs = 4326)
#Geodetic CRS:  WGS 84

#w <- st_geometry(w)
#w <- st_union(w)
#w
#plot(w)


#plot(south)
```

```{r}
```