
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "D:/AGH/INZ/data")
```

#function for running external .Rmd files
```{r}
source_rmd = function(file, ...) {
  tmp_file = tempfile(fileext=".R")
  on.exit(unlink(tmp_file), add = TRUE)
  knitr::purl(file, output=tmp_file)
  source(file = tmp_file, ...)
}
```

```{r}
#source_rmd("../codes/forecast.Rmd")
```

LOADING SAVED WORKSPACE
```{r}
load("manual_real_fore.RData")
source_rmd("D:/AGH/INZ/codes/shapefiles.Rmd")
Sys.setlocale("LC_TIME", "C")
```

########################################################################################################

#FITTING GRIDS

COMPARING RESAMPLE CONFIGURATIONS
```{r}

lon_real_raster = raster(ncol=length(lon_real), nrow=length(lat_real))
lat_real_raster = raster(ncol=length(lon_real), nrow=length(lat_real))
lon_fore_raster = raster(ncol=length(lon_fore), nrow=length(lat_fore))
lat_fore_raster = raster(ncol=length(lon_fore), nrow=length(lat_fore))

values(lon_real_raster) = as.vector(grid_real_spei6[,1])
values(lat_real_raster) = as.vector(grid_real_spei6[,2])
values(lon_fore_raster) = as.vector(grid_fore_spei6[,1])
values(lat_fore_raster) = as.vector(grid_fore_spei6[,2])

par(mfrow=c(2,2))
plot(lon_real_raster)                         
plot(lat_real_raster)
plot(lon_fore_raster)
plot(lat_fore_raster)

#######################################################################
#forecast to real (5->4)
lon_fore_bilinear <- resample(lon_fore_raster, lon_real_raster, method='bilinear')
lat_fore_bilinear <- resample(lat_fore_raster, lat_real_raster, method='bilinear')

ncol(lon_real_raster)

mse1=0
for (i in 1:dim(lon_fore_bilinear)[1])
{
  for (j in 1:dim(lon_fore_bilinear)[2])
  {
    print(i)
    mse1 = mse1 + sqrt((lon_fore_bilinear[i,j] - lon_real_raster[i,j])^2 + (lat_fore_bilinear[i,j] - lat_real_raster[i,j])^2)
  }
}
mse1 = mse1 / (dim(lon_fore_bilinear)[1] * dim(lon_fore_bilinear)[2]) 
mse1 #0.01299204


#######################################################################
#real to forecast (4->5)
lon_real_bilinear <- resample(lon_real_raster, lon_fore_raster, method='bilinear')
lat_real_bilinear <- resample(lat_real_raster, lat_fore_raster, method='bilinear')

ncol(lon_real_bilinear)

mse2=0
for (i in 1:dim(lon_real_bilinear)[1])
{
  for (j in 1:dim(lon_real_bilinear)[2])
  {
    print(i)
    mse2 = mse2 + sqrt((lon_real_bilinear[i,j] - lon_fore_raster[i,j])^2 + (lat_real_bilinear[i,j] - lat_fore_raster[i,j])^2)
  }
}
mse2 = mse2 / (dim(lon_real_bilinear)[1] * dim(lon_real_bilinear)[2]) 
mse2 #0.01299202

mse1
mse2
#smaller MSE for second option (real to forecast)
```

PREPARING RASTERSTACKS

removing 2006
```{r}
july
#july <- july[2:length(july)]
spei_real_s <- c()
spei_fore_s <- c()
```
SPEI1
```{r}
spei1_real_list = list()
spei1_fore_list = list()

grid_fore_spei1 <- expand.grid(lon=lon_fore, lat=lat_fore)
grid_real_spei1 <- expand.grid(lon=lon_real, lat=lat_real)

for (i in july) 
{
  #forecast
  grid_fore_spei1$z<-as.numeric(SPEI1_fore[,,i])
  spei1_fore_raster<-rasterFromXYZ(grid_fore_spei1,crs=4321)
  spei1_fore_list <- append(spei1_fore_list, spei1_fore_raster)
  
  #real
  grid_real_spei1$z<-as.numeric(SPEI1_real[,,i])
  spei1_real_raster<-rasterFromXYZ(grid_real_spei1,crs=4321)
  spei1_real_r2 <- resample(spei1_real_raster, spei1_fore_raster, method='bilinear')
  spei1_real_list <- append(spei1_real_list, spei1_real_r2)
}

real_spei1_stack <- stack(spei1_real_list)
fore_spei1_stack <- stack(spei1_fore_list)
plot(real_spei1_stack)
plot(fore_spei1_stack)

spei_real_s <- append(spei_real_s, real_spei1_stack)
spei_fore_s <- append(spei_fore_s, fore_spei1_stack)
```

SPEI3
```{r}
spei3_real_list = list()
spei3_fore_list = list()

grid_fore_spei3 <- expand.grid(lon=lon_fore, lat=lat_fore)
grid_real_spei3 <- expand.grid(lon=lon_real, lat=lat_real)

for (i in july)
{
  #forecast
  grid_fore_spei3$z<-as.numeric(SPEI3_fore[,,i])
  spei3_fore_raster<-rasterFromXYZ(grid_fore_spei3,crs=4323)
  spei3_fore_list <- append(spei3_fore_list, spei3_fore_raster)
  
  #real
  grid_real_spei3$z<-as.numeric(SPEI3_real[,,i])
  spei3_real_raster<-rasterFromXYZ(grid_real_spei3,crs=4323)
  spei3_real_r2 <- resample(spei3_real_raster, spei3_fore_raster, method='bilinear')
  spei3_real_list <- append(spei3_real_list, spei3_real_r2)
}

real_spei3_stack <- stack(spei3_real_list)
fore_spei3_stack <- stack(spei3_fore_list)
plot(real_spei3_stack)
plot(fore_spei3_stack)

spei_real_s <- append(spei_real_s, real_spei3_stack)
spei_fore_s <- append(spei_fore_s, fore_spei3_stack)
```

SPEI6
```{r}
spei6_real_list = list()
spei6_fore_list = list()

grid_fore_spei6 <- expand.grid(lon=lon_fore, lat=lat_fore)
grid_real_spei6 <- expand.grid(lon=lon_real, lat=lat_real)

for (i in july)
{
  #forecast
  grid_fore_spei6$z<-as.numeric(SPEI6_fore[,,i])
  spei6_fore_raster<-rasterFromXYZ(grid_fore_spei6,crs=4326)
  spei6_fore_list <- append(spei6_fore_list, spei6_fore_raster)
  
  #real
  grid_real_spei6$z<-as.numeric(SPEI6_real[,,i])
  spei6_real_raster<-rasterFromXYZ(grid_real_spei6,crs=4326)
  spei6_real_r2 <- resample(spei6_real_raster, spei6_fore_raster, method='bilinear')
  spei6_real_list <- append(spei6_real_list, spei6_real_r2)
}

real_spei6_stack <- stack(spei6_real_list)
fore_spei6_stack <- stack(spei6_fore_list)
plot(real_spei6_stack)
plot(fore_spei6_stack)

spei_real_s <- append(spei_real_s, real_spei6_stack)
spei_fore_s <- append(spei_fore_s, fore_spei6_stack)

#writeRaster(real_spei3_stack, "rasters/stacks/real_spei3_stack.tif", format="GTiff")
#writeRaster(fore_spei3_stack, "rasters/stacks/forecast_spei3_stack.tif", format="GTiff")


```

SPEI12
```{r}
spei12_real_list = list()
spei12_fore_list = list()

grid_fore_spei12 <- expand.grid(lon=lon_fore, lat=lat_fore)
grid_real_spei12 <- expand.grid(lon=lon_real, lat=lat_real)

for (i in july)
{
  #forecast
  grid_fore_spei12$z<-as.numeric(SPEI12_fore[,,i])
  spei12_fore_raster<-rasterFromXYZ(grid_fore_spei12,crs=43212)
  spei12_fore_list <- append(spei12_fore_list, spei12_fore_raster)
  
  #real
  grid_real_spei12$z<-as.numeric(SPEI12_real[,,i])
  spei12_real_raster<-rasterFromXYZ(grid_real_spei12,crs=43212)
  spei12_real_r2 <- resample(spei12_real_raster, spei12_fore_raster, method='bilinear')
  spei12_real_list <- append(spei12_real_list, spei12_real_r2)
}

real_spei12_stack <- stack(spei12_real_list)
fore_spei12_stack <- stack(spei12_fore_list)
plot(real_spei12_stack)
plot(fore_spei12_stack)

spei_real_s <- append(spei_real_s, real_spei12_stack)
spei_fore_s <- append(spei_fore_s, fore_spei12_stack)
```

```{r}
spei <- c(spei_real_s, spei_fore_s)
spei_rasters <- data.frame(matrix(spei, nrow=4, ncol=2))
colnames(spei_rasters) <- c("real", "forecast")
rownames(spei_rasters) <- c(1,3,6,12)

```

OTHER VARIABLES (tmax, tmin, ppt)

PREPARING RASTERSTACKS

SPEI rasters: 2007 - 2021
TMAX, TMIN, PPT rasters: 2006 - 2021 (because SPEI uses timescales up to 12 months)

TMAX 
```{r}

grid_fore_tmax <- expand.grid(lon=lon_fore, lat=lat_fore)
grid_real_tmax <- expand.grid(lon=lon_real, lat=lat_real)

tmax_real_stacks <- c()
tmax_fore_stacks <- c()

for (i in seq(1,12))
{
  tmax_real_list = list()
  tmax_fore_list = list()

  monthly <- seq((i), length(time_fore), by=12)
  print(monthly)
  for (i in monthly)
  {
    #forecast
    grid_fore_tmax$z<-as.numeric(tmax_fore_array[,,i])
    tmax_fore_raster<-rasterFromXYZ(grid_fore_tmax,crs=4321)
    tmax_fore_list <- append(tmax_fore_list, tmax_fore_raster)
    
    #real
    grid_real_tmax$z<-as.numeric(tmax_real_array[,,i])
    tmax_real_raster<-rasterFromXYZ(grid_real_tmax,crs=4321)
    tmax_real_r2 <- resample(tmax_real_raster, tmax_fore_raster, method='bilinear')
    tmax_real_list <- append(tmax_real_list, tmax_real_r2)
  }
    
  real_tmax_stack <- stack(tmax_real_list)
  fore_tmax_stack <- stack(tmax_fore_list)
  plot(real_tmax_stack)
  plot(fore_tmax_stack)
  tmax_real_stacks <- append(tmax_real_stacks, real_tmax_stack)
  tmax_fore_stacks <- append(tmax_fore_stacks, fore_tmax_stack)
}

tmax <- c(tmax_real_stacks, tmax_fore_stacks)
tmax_rasters <- data.frame(matrix(tmax, nrow=12, ncol=2))
colnames(tmax_rasters) <- c("real", "forecast")
```

TMIN
```{r}
grid_fore_tmin <- expand.grid(lon=lon_fore, lat=lat_fore)
grid_real_tmin <- expand.grid(lon=lon_real, lat=lat_real)

tmin_real_stacks <- c()
tmin_fore_stacks <- c()

for (i in seq(1,12))
{
  tmin_real_list = list()
  tmin_fore_list = list()

  monthly <- seq(i, length(time_fore), by=12)
  print(monthly)
  for (i in monthly)
  {
    #forecast
    grid_fore_tmin$z<-as.numeric(tmin_fore_array[,,i])
    tmin_fore_raster<-rasterFromXYZ(grid_fore_tmin,crs=4321)
    tmin_fore_list <- append(tmin_fore_list, tmin_fore_raster)
    
    #real
    grid_real_tmin$z<-as.numeric(tmin_real_array[,,i])
    tmin_real_raster<-rasterFromXYZ(grid_real_tmin,crs=4321)
    tmin_real_r2 <- resample(tmin_real_raster, tmin_fore_raster, method='bilinear')
    tmin_real_list <- append(tmin_real_list, tmin_real_r2)
  }
    
  real_tmin_stack <- stack(tmin_real_list)
  fore_tmin_stack <- stack(tmin_fore_list)
  plot(real_tmin_stack)
  plot(fore_tmin_stack)
  tmin_real_stacks <- append(tmin_real_stacks, real_tmin_stack)
  tmin_fore_stacks <- append(tmin_fore_stacks, fore_tmin_stack)
}

tmin <- c(tmin_real_stacks, tmin_fore_stacks)
tmin_rasters <- data.frame(matrix(tmin, nrow=12, ncol=2))
colnames(tmin_rasters) <- c("real", "forecast")

```

PPT
```{r}
grid_fore_ppt <- expand.grid(lon=lon_fore, lat=lat_fore)
grid_real_ppt <- expand.grid(lon=lon_real, lat=lat_real)

ppt_real_stacks <- c()
ppt_fore_stacks <- c()

for (i in seq(1,12))
{
  ppt_real_list = list()
  ppt_fore_list = list()

  monthly <- seq(i, length(time_fore), by=12)
  print(monthly)
  for (i in monthly) #same as july_fore
  {
    #forecast
    grid_fore_ppt$z<-as.numeric(ppt_fore_array[,,i])
    ppt_fore_raster<-rasterFromXYZ(grid_fore_ppt,crs=4321)
    ppt_fore_list <- append(ppt_fore_list, ppt_fore_raster)
    
    #real
    grid_real_ppt$z<-as.numeric(ppt_real_array[,,i])
    ppt_real_raster<-rasterFromXYZ(grid_real_ppt,crs=4321)
    ppt_real_r2 <- resample(ppt_real_raster, ppt_fore_raster, method='bilinear')
    ppt_real_list <- append(ppt_real_list, ppt_real_r2)
  }
    
  real_ppt_stack <- stack(ppt_real_list)
  fore_ppt_stack <- stack(ppt_fore_list)
  plot(real_ppt_stack)
  plot(fore_ppt_stack)
  ppt_real_stacks <- append(ppt_real_stacks, real_ppt_stack)
  ppt_fore_stacks <- append(ppt_fore_stacks, fore_ppt_stack)
}

ppt <- c(ppt_real_stacks, ppt_fore_stacks)
ppt_rasters <- data.frame(matrix(ppt, nrow=12, ncol=2))
colnames(ppt_rasters) <- c("real", "forecast")
```






```{r}

save(list=c("both", "north", "south", "pol", "july", "lat_fore", "lon_fore", 
"lat_real", "lon_real", "PET_fore", "PET_real", "ppt_fore_array", "ppt_real_array", 
"SPEI1_fore", "SPEI1_real", "SPEI3_fore", "SPEI3_real", "SPEI6_fore", "SPEI6_real", 
"SPEI12_fore", "SPEI12_real", "time_fore", "time_real", "tmax_fore_array", "tmax_real_array", 
"tmin_fore_array", "tmin_real_array", "spei_rasters", "tmax_rasters", "tmin_rasters", "ppt_rasters"), file="manual_real_fore_rasters.RData")


````