#LOADING ALL NECESSARY PACKAGES
library(ncdf4)
library(sf)
library(zoo)
library(chron)
library(RColorBrewer)
library(lattice)
library(weathermetrics)
library(SPEI)
library(raster)
library(lubridate)
library(rgeos)
